services:
  mysql:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3308:3306"
    networks:
      - app-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
