services:
  app:
    image: tichall111/heartcall:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
    networks:
      - app-network
    volumes:
      - ./src/main/resources/heartcall-c0e63-firebase-adminsdk-fbsvc-d37770e367.json:/app/src/main/resources/heartcall-c0e63-firebase-adminsdk-fbsvc-d37770e367.json
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
