spring:
  datasource:
    url: jdbc:mysql://${DATASOURCE_URL}/heartcall
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

coolsms:
  api-key: ${SMS_API_KEY}
  secret-key: ${SMS_SECRET_KEY}
  provider: ${SMS_PROVIDER}
  sender: ${SMS_SENDER}
